spring:
  application:
    name: TrainingInfo
  config:
    import: optional:configserver:http://localhost:8088
#  datasource:
#    url: jdbc:mysql://localhost:3306/TMA
#    username: root
#    password: pass@word1
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#      show-sql: true
trainer:
  service:
    url: http://localhost:9099
