#spring:
#  datasource:
#    url: jdbc:sqlserver://sb2.database.windows.net:1433;database=expense;user=admin123@sb2;password=8217577409@Lee;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
#    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    database-platform: org.hibernate.dialect.SQLServerDialect